[project]
name = "spiritplanner"
version = "1.0.0"
requires-python = ">=3.10"
dependencies = [
  "flet==0.80.2",
  "firebase-admin==7.1.0",
  "python-dotenv==1.2.1",
  "repath==0.9.0",
]

[tool.flet.compile]
app = true
packages = true
cleanup = true

[tool.flet.app]
path = "app"
module = "main.py"
